#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-paranamer
Version  : 2.8
Release  : 3
URL      : https://github.com/paul-hammant/paranamer/archive/paranamer-parent-2.8.tar.gz
Source0  : https://github.com/paul-hammant/paranamer/archive/paranamer-parent-2.8.tar.gz
Source1  : https://repo1.maven.org/maven2/com/thoughtworks/paranamer/paranamer-parent/2.3/paranamer-parent-2.3.pom
Source2  : https://repo1.maven.org/maven2/com/thoughtworks/paranamer/paranamer-parent/2.8/paranamer-parent-2.8.pom
Source3  : https://repo1.maven.org/maven2/com/thoughtworks/paranamer/paranamer/2.3/paranamer-2.3.jar
Source4  : https://repo1.maven.org/maven2/com/thoughtworks/paranamer/paranamer/2.3/paranamer-2.3.pom
Source5  : https://repo1.maven.org/maven2/com/thoughtworks/paranamer/paranamer/2.8/paranamer-2.8.jar
Source6  : https://repo1.maven.org/maven2/com/thoughtworks/paranamer/paranamer/2.8/paranamer-2.8.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: mvn-paranamer-data = %{version}-%{release}

%description
# ![ParaNamer](http://paulhammant.com/images/ParaNamer.jpg)
## Method Parameter Name Access for Java*

%package data
Summary: data components for the mvn-paranamer package.
Group: Data

%description data
data components for the mvn-paranamer package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/thoughtworks/paranamer/paranamer-parent/2.3
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/thoughtworks/paranamer/paranamer-parent/2.3

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/thoughtworks/paranamer/paranamer-parent/2.8
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/thoughtworks/paranamer/paranamer-parent/2.8

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/thoughtworks/paranamer/paranamer/2.3
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/com/thoughtworks/paranamer/paranamer/2.3

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/thoughtworks/paranamer/paranamer/2.3
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/com/thoughtworks/paranamer/paranamer/2.3

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/thoughtworks/paranamer/paranamer/2.8
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/com/thoughtworks/paranamer/paranamer/2.8

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/thoughtworks/paranamer/paranamer/2.8
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/com/thoughtworks/paranamer/paranamer/2.8


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/thoughtworks/paranamer/paranamer-parent/2.3/paranamer-parent-2.3.pom
/usr/share/java/.m2/repository/com/thoughtworks/paranamer/paranamer-parent/2.8/paranamer-parent-2.8.pom
/usr/share/java/.m2/repository/com/thoughtworks/paranamer/paranamer/2.3/paranamer-2.3.jar
/usr/share/java/.m2/repository/com/thoughtworks/paranamer/paranamer/2.3/paranamer-2.3.pom
/usr/share/java/.m2/repository/com/thoughtworks/paranamer/paranamer/2.8/paranamer-2.8.jar
/usr/share/java/.m2/repository/com/thoughtworks/paranamer/paranamer/2.8/paranamer-2.8.pom
